name: CV Preview

on:
  pull_request:
    paths:
      - "**.typ"

jobs:
  build-and-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v22

      - name: Build CV in PDF and PNG formats
        run: |
          nix develop --command cv build
          nix develop --command cv preview

      - name: Encode PNGs to base64
        id: encode_pngs
        run: |
          PNG_FILES=$(ls cv_*.png | sort -V)
          BASE64_PNGS=""
          for file in $PNG_FILES; do
            BASE64_PNG=$(base64 -w 0 "$file")
            BASE64_PNGS+="$file:$BASE64_PNG,"
          done
          echo "base64_pngs=${BASE64_PNGS%,}" >> $GITHUB_OUTPUT

      - name: Upload CV PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: cv-pdf
          path: cv.pdf

      - name: Comment PR with preview and download link
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const artifactUrl = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`;
            const base64Pngs = '${{ steps.encode_pngs.outputs.base64_pngs }}'.split(',');

            let comment = `## CV Preview\n\n`;

            base64Pngs.forEach((pngData) => {
              const [filename, base64] = pngData.split(':');
              comment += `### ${filename}\n\n`;
              comment += `![CV Preview](data:image/png;base64,${base64})\n\n`;
            });

            comment += `[Download Full CV (PDF)](${artifactUrl})`;

            github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.name,
              body: comment
            });
