name: CV Preview

on:
  pull_request:
    paths:
      - "cv/**"

jobs:
  build-and-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v22

      - name: Build CV
        run: |
          nix develop --command cv build

      - name: Upload CV as artifact
        uses: actions/upload-artifact@v4
        with:
          name: cv
          path: cv.pdf

      - name: Comment PR with artifact link
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const artifactUrl = `https://github.com/${context.repo.owner}/${context.repo.name}/actions/runs/${context.runId}`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.name,
              body: `CV preview has been built. You can download it from the artifacts of this workflow run.\n\nArtifact URL: ${artifactUrl}`
            })
