name: Publish CV Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

env:
  CV_NAME: Roman_Vanesyan_CV

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27

      - name: Build CV
        run: |
          nix develop --command cv build
          mv cv.pdf "${{ env.CV_NAME }}.pdf"

      - name: Upload CV PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: cv-pdf
          path: ${{ env.CV_NAME }}.pdf

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.CV_NAME }}.pdf
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Update Latest Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest Release
          files: ${{ env.CV_NAME }}.pdf
          prerelease: false
          draft: false